services:
  api:
    build: .
    container_name: org_catalog_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
        alembic upgrade head &&
        python -m data.populate_db &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "